services:
  dbms:
    image: ${DB_IMAGE}
    environment:
      TZ: ${OS_TIMEZONE}
    healthcheck:
      test: ["CMD-SHELL", "${DB_HEALTHCHECK}"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}

  schemaspy:
    image: schemaspy/schemaspy
    volumes:
      - ./schemaspy.properties:/schemaspy.properties
      - ../docs/schemaspy:/output
